from enum import Enum

class EntryStrategy(Enum):
    MACD_STATE = "MACD_STATE"
    MACDHIST_STATE = "MACDHIST_STATE"
    MACDHIST_EMA_V1 = "MACDHIST_EMA_V1"
    PRICE_CROSS_EMA_RSI = "PRICE_CROSS_EMA_RSI"
    PREVIOUS_CANDLE = "PREVIOUS_CANDLE"
    MOMENTUM_TREND_FILTERED = "MOMENTUM_TREND_FILTERED"
    WICK_MEAN_REVERSION = "WICK_MEAN_REVERSION"
    GUARANTEED_SCALP = "GUARANTEED_SCALP"
    SCALP_BODY_FILTER_MOMENTUM = "SCALP_BODY_FILTER_MOMENTUM"

# EOF
