from enum import Enum

class EntryStrategy(Enum):
    MACD_STATE = "MACD_STATE"
    MACDHIST_STATE = "MACDHIST_STATE"
    MACDHIST_EMA_V1 = "MACDHIST_EMA_V1"
    PRICE_CROSS_EMA_RSI = "PRICE_CROSS_EMA_RSI"

# EOF
