from enum import Enum

class ExitStrategy(Enum):
    TP_SL = "TP_SL"
    MACD_STATE = "MACD_STATE"
    MACDHIST_STATE = "MACDHIST_STATE"
    CANDLE_CLOSE_WITH_SL = "CANDLE_CLOSE_WITH_SL"
    CANDLE_CLOSE = "CANDLE_CLOSE"
    WICK_TARGET = "WICK_TARGET"
    COUNTDOWN_MAX_LOSS = "COUNTDOWN_MAX_LOSS"

# EOF
